// Floating preview card shown when hovering (or keyboard-focusing) a link.
// Previews are pre-captured snapshots: previews/manifest.json maps each href
// to an image generated by scripts/capture-link-previews.mjs (npm run
// previews). Links without a manifest entry simply show no card. Mouse-only
// on hover (touch taps navigate immediately), and hidden entirely on
// hover-incapable devices via css/link-preview.css.

// Hover-intent tuning: every link (first or subsequent) requires the same
// deliberate dwell before its card appears.
var SHOW_DELAY = 700;
var HIDE_DELAY = 120;

export function initLinkPreviews() {
  var manifest = null;
  var card = null;
  var image = null;
  var titleEl = null;
  var domainEl = null;
  var showTimer = 0;
  var hideTimer = 0;
  var currentLink = null; // the link whose card is currently visible
  var preloader = new Image(); // warms the snapshot during the hover dwell

  fetch('/previews/manifest.json')
    .then(function (response) { return response.ok ? response.json() : null; })
    .then(function (data) { manifest = data; })
    .catch(function () { /* no previews generated yet */ });

  function ensureCard() {
    if (card) {
      return;
    }

    card = document.createElement('div');
    card.className = 'link-preview';
    card.setAttribute('aria-hidden', 'true');

    image = document.createElement('img');
    image.className = 'link-preview__image';
    image.alt = '';

    var meta = document.createElement('div');
    meta.className = 'link-preview__meta';
    titleEl = document.createElement('span');
    titleEl.className = 'link-preview__title';
    domainEl = document.createElement('span');
    domainEl.className = 'link-preview__domain';
    meta.appendChild(titleEl);
    meta.appendChild(domainEl);

    card.appendChild(image);
    card.appendChild(meta);
    document.body.appendChild(card);
  }

  function entryFor(link) {
    if (!manifest) {
      return null;
    }

    var href = link.getAttribute('href');
    if (!href || (!href.startsWith('http') && !href.startsWith('/'))) {
      return null;
    }

    return manifest[href] || null;
  }

  function positionCard(link) {
    var rect = link.getBoundingClientRect();
    var cardWidth = card.offsetWidth;
    var cardHeight = card.offsetHeight;
    var margin = 12;

    var x = rect.left + rect.width / 2 - cardWidth / 2;
    x = Math.max(8, Math.min(x, window.innerWidth - cardWidth - 8));

    var above = rect.top - cardHeight - margin >= 8;
    var y = above ? rect.top - cardHeight - margin : rect.bottom + margin;

    card.style.left = x.toFixed(1) + 'px';
    card.style.top = y.toFixed(1) + 'px';
    card.classList.toggle('is-below', !above);
  }

  function showCard(link, entry) {
    ensureCard();

    var href = link.getAttribute('href');
    if (image.getAttribute('src') !== entry.image) {
      // Clear the previous snapshot first: an <img> keeps displaying its old
      // bitmap until the new src finishes loading, which would flash the
      // prior link's preview. The card is hidden at this point, so the swap
      // is invisible; until the new image arrives the placeholder shows.
      image.removeAttribute('src');
      image.src = entry.image;
    }
    titleEl.textContent = entry.title || '';
    try {
      domainEl.textContent = new URL(href, window.location.origin).hostname;
    } catch (error) {
      domainEl.textContent = '';
    }

    positionCard(link);
    card.classList.add('is-visible');
    currentLink = link;
  }

  function hideCard() {
    if (card) {
      card.classList.remove('is-visible');
    }
    currentLink = null;
  }

  function scheduleShow(link) {
    var entry = entryFor(link);
    if (!entry) {
      return;
    }

    window.clearTimeout(showTimer);
    window.clearTimeout(hideTimer);

    // Back on the link whose card is already up: just keep it showing.
    if (currentLink === link) {
      return;
    }

    // Fetch the snapshot now so it is (almost always) ready when the dwell
    // elapses, instead of loading only once the card is already visible.
    preloader.src = entry.image;

    // A different link: drop the old card at once and require a fresh dwell.
    hideCard();
    showTimer = window.setTimeout(function () {
      showCard(link, entry);
    }, SHOW_DELAY);
  }

  function scheduleHide() {
    window.clearTimeout(showTimer);
    window.clearTimeout(hideTimer);
    hideTimer = window.setTimeout(hideCard, HIDE_DELAY);
  }

  document.addEventListener('pointerover', function (event) {
    if (event.pointerType && event.pointerType !== 'mouse') {
      return;
    }

    var link = event.target.closest('a[href]');
    if (link) {
      scheduleShow(link);
    }
  });

  document.addEventListener('pointerout', function (event) {
    var link = event.target.closest('a[href]');
    if (!link) {
      return;
    }

    var relatedTarget = event.relatedTarget;
    if (relatedTarget && link.contains(relatedTarget)) {
      return;
    }

    scheduleHide();
  });

  document.addEventListener('focusin', function (event) {
    var link = event.target.closest('a[href]');
    if (link) {
      scheduleShow(link);
    }
  });

  document.addEventListener('focusout', function () {
    scheduleHide();
  });

  window.addEventListener('scroll', hideCard, { passive: true });
  window.addEventListener('resize', hideCard);
}
